### ISSUE TITLE
FEATURE REQUEST: ability to use mutiple rules at once with the terminate action

### ISSUE THREAD

**Issue by xinity** [Issif/falco-talon#107]
it could be very useful to give talon the ability to apply several rules at once with the terminate action.

For example:
- creation network policy
- terminate pod

this could drastically improve the security autoremediation possibility :)

**Comment by Issif** [comment]
I added a `before` setting which allow to run an action before all others, even those with continue=false.

For example, if you match 2 rules, one to create a netpol and another to terminate. As the netpol action has before=true, it will run before the termination, and as the termination has continue=false by default, it will stop there.

**Comment by Issif** [comment]
we're all good
