### ISSUE TITLE
FEATURE REQUEST: ability to work with kubernetes audit fields

### ISSUE THREAD

**Issue by igoritos22** [Issif/falco-talon#115]
It would be really cool if there was a possibility for talon to work with k8s_audit plugin fields. For example:

- ka.target.name
- ka.target.namespace

I forked the repository and made the change and was able to terminate the k8s_audit plugin rules.

Actually talon has can work only with k8s.ns.name and k8s.pod.name.

**Comment by Issif** [comment]
Hello @igoritos22,

For now, I focused Talon on the rules based on syscalls, all actions concerned the pods. By integrating the `k8saudit` plugin's fields, I need to integrate more actions, like the deletion of the resources. It's in my todo for sure, I just wanted to stabilize the core before. What's your use case?

**Comment by igoritos22** [comment]
My use case is very particular. Here I use k8s_audit in my workload and recently I needed to restrict some users to exec the pods in my cluster. As I can only get the exact user who executed the exec via k8s_audit, I needed to change the falco field to ka.target.name and ka.target.namespace.

By the way, if you have any suggestions on how I can achieve this working with syscall, I would love to know

**Comment by Issif** [comment]
Thank you for your support.

Falco is not really made to restrict things, you should take a look at [Kyverno](https://kyverno.io/) for that, they propose policies to block the Exec.
With the syscalls, you will not be able to know which user called the k8s api to do an exec, but you can detect than a shell has been spawned inside the container.

I'll integrate the `k8saudit` source asap, my idea is to create a new actionner `kubernetes:delete`, if a rule triggered concerns a resource, it will delete it (anyone, configmap, secret, deployment, daemonset, etc). It's different from `kubernetes:terminate` which concern only the pods and the syscalls.

**Comment by igoritos22** [comment]
Very nice @Issif . Thanks for all explanation.

**Comment by Issif** [comment]
The actionner `kubernetes:delete` is implemented and the docs is [here](https://docs.falco-talon.org/docs/actionners/list/#kubernetesdelete).
